language: node.js
install:
 - wget https://s3-us-west-1.amazonaws.com/lightbody-bmp/browsermob-proxy-2.0-beta-9-bin.zip
 - unzip browsermob-proxy-2.0-beta-9-bin.zip
 - browsermob-proxy-2.0-beta-9/bin/browsermob-proxy &
 - npm install
 - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - 
 - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
 - sudo apt-get update
 - sudo apt-get install google-chrome-stable
script:
 - mocha --timeout 20000 --globals Intl,IntlPolyfill,ErrorHandler test/tests.js

